version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    command: npm run dev
  # db:
  #   image: postgres:latest
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=mydb
  #   volumes:
  #     - db-data:/var/lib/postgresql/data

# volumes:
  # db-data:
