services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    command: npm run dev

  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=emil-portfolio
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - ./backend:/app
    command: air -c .air.toml
    depends_on:
      - postgres
