# This file is used for local development
services:
  web-app:
    build:
      context: .
      target: dev
    restart: unless-stopped
    ports:
      - 80:5173
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env
    command: npm run dev

  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - .env.db
