version: '3'

services:
  frontend:
    build:
      context: ./frontend-2
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5173:5173
    volumes:
      - ./frontend-2:/app
    environment:
      - NODE_ENV=development
    command: npm run dev
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - ./db:/app
    command: air -c .air.toml
