services:

  frontend:
    build:
      context: .
      target: dev
    restart: unless-stopped
    ports:
      - 80:5173
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
    command: npm run dev

  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=emil-portfolio
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
