# AIR.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/engine ./cmd/main.go"
bin = "tmp/app"
full_bin = "./tmp/engine http"

log = "tmp/air.log"

include_ext = ["go", "yaml", "tolm"]
exclude_dir = ["tmp", "vendor"]

delay = 500 # ms

[log]
time = true

[misc]
clean_on_exit = true
