root = "."
tmp_dir = "tmp"

[build]
	cmd = "go build -o ./tmp/main ./cmd/main.go"
	bin = "tmp/main"
	full_bin = "./tmp/main http"

	log = "tmp/air.log"

	include_ext = ["go"]
	exclude_dir = ["tmp", "vendor"]

	delay = 500 # ms

[log]
	time = true

[misc]
	clean_on_exit = true
